### ISSUE TITLE
Use Kotlin's Charset instead of java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by little-fish** [redundent/kotlin-xml-builder#9]
The library is not working on Android with API <= 19.
`java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at org.redundent.kotlin.xml.Node.<init>(XmlBuilder.kt:70)
        at org.redundent.kotlin.xml.XmlBuilderKt.xml(XmlBuilder.kt:448)
        at org.redundent.kotlin.xml.XmlBuilderKt.xml$default(XmlBuilder.kt:447)`
[Refference](https://developer.android.com/reference/java/nio/charset/StandardCharsets).
Thank you.

**Comment by redundent** [comment]
Thanks @little-fish !
This is merged and published as version 1.4.4

**Comment by little-fish** [comment]
That was fast!!! Thank you for quick merge. Working great, so I can get rid of my messy workaround :)
